### ISSUE TITLE
Is it dead or alive?

### ISSUE THREAD

**Issue by AqlaSolutions** [SmartInvoiceXYZ/smart-invoice#232]
Hi, I'm browsing the official site and all the videos on the landing page are broken, also the discord link is expired. So is it dead?

**Comment by benedictvscriticus** [comment]
Hi @AqlaSolutions ! Thank you for your comment and pointing out the broken links. We are aware of the issue, because we are going through a major upgrade at the moment, which involves some changes to 3rd party providers, including Discord and Youtube. If you want to join our Discord server, you can use this in the meantime https://discord.gg/eDb4frFuym.

If I may ask, what do you want to use SmartInvoice for?

**Comment by dan13ram** [comment]
Closing this as its no longer relevant, please reopen or raise a new issue if you face any specific bugs.
